version: "3"
services:
  client:
    build:
      context: .
    container_name: client
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start"
    volumes:
      - "${PWD}/client:/client"
    working_dir: /client
    environment:
     - NODE_ENV=production
     - SASS_PATH=node_modules:src
    extra_hosts:
      - "docker-api.com.au:192.168.2.151"
    networks:
      loungebuddy-network:
        ipv4_address: 192.168.2.150
  api:
    build:
      context: .
    container_name: api
    ports:
      - "1880:1880"
      - "9229:9229"
    command: sh -c "npm run start"
    volumes:
      - "${PWD}/api:/api"
    working_dir: /api
    environment:
     - NODE_ENV=production
    extra_hosts:
      - "docker-mongo.com.au:192.168.2.152"
    networks:
      loungebuddy-network:
        ipv4_address: 192.168.2.151
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /data/db
    networks:
      loungebuddy-network:
        ipv4_address: 192.168.2.152
    ports:
      - "27017:27017" 
networks:
   loungebuddy-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24